### ISSUE TITLE
GUI界面纠删码卷无法访问

### ISSUE THREAD

**Issue by migejiejie** [cubefs/cubefs-dashboard#20]
纠删码卷按钮是灰的
看文档上说是没有关联纠删码集群时按钮才是灰的，我这个关联纠删码集群后也是灰的，无法访问。

![1705911260082](https://github.com/cubefs/cubefs-dashboard/assets/55675123/d4a904cd-0ade-425c-af31-9fd8a39ee291)

![94fc4486937c7ea136f5e79fd298fb3](https://github.com/cubefs/cubefs-dashboard/assets/55675123/4d48f95c-6527-42fa-8433-773d507a1d25)

**Comment by lily-lee** [comment]
#17 第2点
